name: error

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "::error file=README.md,line=10,col=15::Something went wrong"
          exit 1
