name: error

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-16.04
    steps:
      - name: test
        run: |
          echo -n '::error file=README.md,line=1::'
          ruby -e 'puts rand'
          exit 1
